# Generated by Django 3.0.7 on 2020-06-18 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Notification',
        ),
        migrations.DeleteModel(
            name='LendNotification',
        ),
    ]
